"""empty message

Revision ID: d6101c10c064
Revises:
Create Date: 2026-01-30 04:30:22.975723

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6101c10c064"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("doc_url", sa.String(), nullable=False),
        sa.Column("full_summary", sa.Text(), nullable=True),
        sa.Column(
            "full_text_search",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('russian', full_summary)", persisted=True
            ),
            nullable=True,
        ),
        sa.Column("summary_embedding", Vector(384), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CREATED",
                "CHUNKED",
                "PROCESSED",
                "SUCCESS",
                "FAILED",
                name="documentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("doc_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_doc_embedding",
        "document",
        ["summary_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"summary_embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_doc_search_vector",
        "document",
        ["full_text_search"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_document_id"), "document", ["id"], unique=True)
    op.create_table(
        "chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column(
            "full_text_search",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('russian', text)", persisted=True),
            nullable=True,
        ),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("summary_embedding", Vector(384), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_id"), "chunk", ["id"], unique=True)
    op.create_index(
        "ix_doc_chunks_embedding",
        "chunk",
        ["summary_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"summary_embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_doc_chunks_search_vector",
        "chunk",
        ["full_text_search"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_doc_chunks_search_vector",
        table_name="chunk",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_doc_chunks_embedding",
        table_name="chunk",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_chunk_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_document_id"), table_name="document")
    op.drop_index(
        "ix_doc_chunks_search_vector",
        table_name="document",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_doc_chunks_embedding",
        table_name="document",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("document")
    # ### end Alembic commands ###
